queue_rules:
  - name: main
    batch_size: 5
    merge_method: squash
    checks_timeout: 15 m 30 s
    max_checks_retries: 5
    update_method: rebase
    batch_max_wait_time: 15 m 34 s
    batch_max_failure_resolution_attempts: 10
    queue_conditions:
      - conflict = false
      - or:
          - author = renovate
          - label = automerge
