// Auto-split from server.rs for cohesion. See server/mod.rs.
use super::*;

impl ServerHandler for BashServer {
    fn get_info(&self) -> ServerInfo {
        ServerInfo::new(ServerCapabilities::builder().enable_tools().build())
            .with_server_info(Implementation::new(
                "harnx-bash-tools",
                env!("CARGO_PKG_VERSION"),
            ))
            .with_instructions(
                "Shell command MCP server with output truncation and retrievable temp logs.",
            )
    }

    async fn list_tools(
        &self,
        _request: Option<PaginatedRequestParams>,
        _context: RequestContext<RoleServer>,
    ) -> Result<ListToolsResult, ErrorData> {
        let mut tools = vec![
            Tool::new(
                "exec",
                "Execute a command and return truncated combined stdout/stderr. When output is cropped, stdout/stderr temp log files are included for later retrieval. Prefer head_lines/tail_lines/max_output_bytes params over piping to head/tail in the command string. Supports shebang lines: if the command starts with #!, the script is written to a temp file and executed with the named interpreter (python3, node, ruby, etc.) — prefer this over python3 -c or node -e for multi-line scripts.",
                Map::new(),
            )
            .with_input_schema::<ExecCommandParams>()
            .with_meta(call_template_meta(tool_templates::EXEC_CALL)),
            Tool::new(
                "read_exec_log",
                "Read a temp stdout/stderr log file generated by this bash server. Use execution_id from exec/wait response with stream 'stdout' or 'stderr'. Supports offset/limit/tail/grep/head_lines/tail_lines/max_output_bytes, but only for server-owned temp logs.",
                Map::new(),
            )
            .with_input_schema::<ReadExecLogParams>()
            .with_meta(call_template_meta(tool_templates::READ_EXEC_LOG_CALL)),
            Tool::new(
                "spawn",
                "Spawn a background command. Returns an execution_id and log file paths immediately without waiting for the command to finish. Output is written to separate stdout.log and stderr.log files. Use 'wait' to check for completion and 'terminate' to stop it. Supports shebang lines: if the command starts with #!, the script is executed with the named interpreter automatically.",
                Map::new(),
            )
            .with_input_schema::<SpawnCommandParams>()
            .with_meta(call_template_meta(tool_templates::SPAWN_CALL)),
            Tool::new(
                "wait",
                "Wait for a spawned background process to exit. Returns the exit code, output metrics, and truncated output. If the process does not exit within the timeout, returns its current status and partial output without killing it. Use head_lines/tail_lines/grep to filter output rather than post-processing with shell tools.",
                Map::new(),
            )
            .with_input_schema::<WaitParams>()
            .with_meta(call_template_meta(tool_templates::WAIT_CALL)),
            Tool::new(
                "terminate",
                "Send a signal to a spawned background process. Default signal is SIGTERM. Supported signals: SIGTERM, SIGKILL, SIGINT, SIGHUP.",
                Map::new(),
            )
            .with_input_schema::<TerminateParams>()
            .with_meta(call_template_meta(tool_templates::TERMINATE_CALL)),
            Tool::new(
                "rollback_file",
                "Restore a repository to a prior harnx history snapshot. Pass the commit SHA from the 'commit <sha>' line at the top of a prior tool response's diff as the commit_id parameter.",
                Map::new(),
            )
            .with_input_schema::<RollbackParams>()
            .with_meta(call_template_meta(tool_templates::ROLLBACK_FILE_CALL)),
        ];
        tools.extend(self.tool_templates().map(|(name, registered)| {
            Tool::new(
                name.clone(),
                registered.description.clone(),
                registered.input_schema.clone(),
            )
            .with_meta(call_template_meta(name))
        }));
        Ok(ListToolsResult::with_all_items(tools))
    }

    async fn call_tool(
        &self,
        request: CallToolRequestParams,
        _context: RequestContext<RoleServer>,
    ) -> Result<CallToolResponse, ErrorData> {
        self.dispatch_call_tool(request, _context)
            .await
            .map(Into::into)
    }

    async fn on_roots_list_changed(&self, _context: NotificationContext<RoleServer>) {}
}

impl BashServer {
    /// The tool dispatch, which always finishes in a single step.
    ///
    /// `call_tool` must return `CallToolResponse`, whose other variants cover
    /// elicitation and long-running tasks that this server does not use.
    /// Dispatching separately keeps every arm returning a plain
    /// `CallToolResult`.
    async fn dispatch_call_tool(
        &self,
        request: CallToolRequestParams,
        _context: RequestContext<RoleServer>,
    ) -> Result<CallToolResult, ErrorData> {
        match request.name.as_ref() {
            "exec" => {
                let params = parse_arguments::<ExecCommandParams>(request.arguments)?;
                self.exec_command_impl(params).await
            }
            "read_exec_log" => {
                let params = parse_arguments::<ReadExecLogParams>(request.arguments)?;
                self.read_exec_log_impl(params).await
            }
            "spawn" => {
                let params = parse_arguments::<SpawnCommandParams>(request.arguments)?;
                self.spawn_impl(params).await
            }
            "wait" => {
                let params = parse_arguments::<WaitParams>(request.arguments)?;
                self.wait_impl(params).await
            }
            "terminate" => {
                let params = parse_arguments::<TerminateParams>(request.arguments)?;
                self.terminate_impl(params).await
            }
            "rollback_file" => {
                let params = parse_arguments::<RollbackParams>(request.arguments)?;
                self.rollback_file_impl(params).await
            }
            template if self.has_tool_template(template) => {
                self.invoke_template(template, &request.arguments.unwrap_or_default())
                    .await
            }
            other => Err(ErrorData::invalid_params(
                format!("unknown tool: {other}"),
                None,
            )),
        }
    }
}
