//! `LlamaServerClient` — Client trait implementation backed by a managed
//! llama-server subprocess communicating over a Unix domain socket.
//!
//! Uses `hyperlocal` for UDS transport, reusing OpenAI request body building
//! and response parsing logic from `crate::openai`.
//!
//! ## Design Note
//!
//! The struct `LlamaServerClient` is generated by the `register_client!` macro
//! (in lib.rs) with fields `{ config: LlamaServerConfig, model: Model }`.
//! This file provides additional implementation for the generated struct,
//! specifically:
//! - `PROMPTS: [PromptAction<'static>; 0]` (no interactive setup needed)
//! - Helper methods for UDS transport (socket_path, hyper client, POST)
//! - `impl Client for LlamaServerClient` with chat completions (streaming + non-streaming)
//!
//! Process management is handled via a global registry (in process.rs) that
//! ensures one `LlamaServerProcessManager` per unique subprocess config,
//! preserving single-flight spawn semantics across all client instances.

#[cfg(unix)]
use crate::{catch_error, ChatCompletionsData, ChatCompletionsOutput, Model, PromptAction, SseHandler};
#[cfg(unix)]
use anyhow::{Context, Result};
#[cfg(unix)]
use bytes::Bytes;
#[cfg(unix)]
use http_body_util::{BodyExt, Full};
#[cfg(unix)]
use hyper::Uri;
#[cfg(unix)]
use hyper_util::{client::legacy::Client, rt::TokioExecutor};
#[cfg(unix)]
use hyperlocal::{UnixConnector, Uri as UnixUri};
#[cfg(unix)]
use serde_json::Value;
#[cfg(unix)]
use std::path::PathBuf;

#[cfg(unix)]
use log::debug;

// Import OpenAI parsing/state types (made pub(crate) in openai.rs)
#[cfg(unix)]
use crate::openai::{
    openai_build_chat_completions_body, openai_emit_pending_tool_call,
    openai_extract_chat_completions, openai_handle_stream_event, OpenAiStreamState,
};

/// No interactive prompts needed for llama-server.
/// Configuration is file-based (model_path, binary_path, etc.).
#[cfg(unix)]
impl crate::LlamaServerClient {
    pub const PROMPTS: [PromptAction<'static>; 0] = [];
}

#[cfg(unix)]
impl crate::LlamaServerClient {
    /// Returns the socket path, spawning the server if necessary.
    ///
    /// Uses the global manager registry to ensure single-flight initialization.
    /// Sources per-model fields from the selected model's `ModelData`.
    async fn get_socket_path(&self) -> Result<PathBuf> {
        use super::process::{get_or_create_manager, LlamaServerProcessConfig};

        let model_data = self.model.data();

        // Resolve the model source from the selected model. Treat blank /
        // whitespace-only values as absent so they don't win the precedence and
        // forward an empty `-m ""` / `-hf ""` to llama-server.
        let model_path = model_data
            .model_path
            .as_deref()
            .map(str::trim)
            .filter(|p| !p.is_empty());
        let hf_repo = model_data
            .hf_repo
            .as_deref()
            .map(str::trim)
            .filter(|r| !r.is_empty());

        use super::process::ModelSource;
        use std::path::PathBuf;

        let model_source = if let Some(p) = model_path {
            ModelSource::LocalPath(PathBuf::from(p))
        } else if let Some(repo) = hf_repo {
            ModelSource::HfRepo(repo.to_string())
        } else {
            // No model_path or hf_repo: treat the model's name as a HuggingFace
            // repo spec so `llama-server -hf <name>` can auto-download it.
            let repo = self.model.real_name().to_string();
            debug!(
                "llama-server model '{}' has no model_path or hf_repo; using its name as a HuggingFace repo (-hf {repo})",
                self.model.name()
            );
            ModelSource::HfRepo(repo)
        };

        // Translate model fields to process config
        let process_config = LlamaServerProcessConfig {
            model_source,
            binary_path: self.config.binary_path.as_ref().map(PathBuf::from),
            socket_path: model_data.socket_path.as_ref().map(PathBuf::from),
            context_size: model_data.ctx_size,
            gpu_layers: model_data.n_gpu_layers.map(|n| n as i32),
            threads: model_data.threads,
            extra_args: model_data.extra_args.clone().unwrap_or_default(),
            ready_timeout: super::process::DEFAULT_READY_TIMEOUT,
        };

        // Get or create manager from global registry
        let manager = get_or_create_manager(&process_config)?;
        let running = manager.ensure_ready().await?;
        Ok(running.socket_path().to_owned())
    }

    /// Build a hyper client for UDS communication.
    ///
    /// Creates a fresh client per call. `UnixConnector` is cheap to construct;
    /// each request opens a new `tokio::net::UnixStream`.
    fn build_hyper_client() -> Client<UnixConnector, Full<Bytes>> {
        Client::builder(TokioExecutor::new()).build(UnixConnector)
    }

    /// Perform a non-streaming POST to the llama-server socket.
    ///
    /// - `path`: HTTP path (e.g., `/v1/chat/completions`)
    /// - `body`: JSON request body (already includes `stream: false`)
    ///
    /// Returns the response body bytes, or an error for non-2xx status codes.
    async fn post_json(&self, path: &str, body: &Value) -> Result<Bytes> {
        let socket_path = self.get_socket_path().await?;
        let client = Self::build_hyper_client();

        let uri: Uri = UnixUri::new(&socket_path, path).into();
        let body_bytes = serde_json::to_vec(body)?;
        let req = hyper::Request::post(uri)
            .header("content-type", "application/json")
            .body(Full::new(Bytes::from(body_bytes)))?;

        let mut res = client.request(req).await?;
        let status = res.status();

        // Collect the response body
        let body_bytes = res
            .body_mut()
            .collect()
            .await
            .context("Failed to read response body")?
            .to_bytes();

        if !status.is_success() {
            // Try to parse as JSON for error handling; fall back to raw body
            let data: Value = serde_json::from_slice(&body_bytes).unwrap_or_else(
                |_| serde_json::json!({ "error": String::from_utf8_lossy(&body_bytes) }),
            );
            // Use standard error parsing (retry_after not applicable over UDS)
            catch_error(&data, status.as_u16(), None)?;
        }

        Ok(body_bytes)
    }

    /// Perform a streaming POST to the llama-server socket.
    ///
    /// Returns SSE events incrementally via the provided `SseHandler`.
    /// The handler checks `aborted()` before processing each event.
    async fn post_json_streaming(
        &self,
        path: &str,
        body: &Value,
        handler: &mut SseHandler,
    ) -> Result<()> {
        let socket_path = self.get_socket_path().await?;
        let client = Self::build_hyper_client();

        let uri: Uri = UnixUri::new(&socket_path, path).into();
        let body_bytes = serde_json::to_vec(body)?;
        let req = hyper::Request::post(uri)
            .header("content-type", "application/json")
            .body(Full::new(Bytes::from(body_bytes)))?;

        let mut res = client.request(req).await?;
        let status = res.status();

        if !status.is_success() {
            // Drain error body and report
            let body_bytes = res
                .body_mut()
                .collect()
                .await
                .context("Failed to read error response body")?
                .to_bytes();
            let data: Value = serde_json::from_slice(&body_bytes).unwrap_or_else(
                |_| serde_json::json!({ "error": String::from_utf8_lossy(&body_bytes) }),
            );
            catch_error(&data, status.as_u16(), None)?;
        }

        // Incrementally consume the SSE stream
        let mut state = OpenAiStreamState::default();
        let mut sse_buffer = Vec::new();

        while let Some(frame) = res.body_mut().frame().await {
            if handler.aborted() {
                break;
            }

            let frame = frame.context("Failed to read SSE frame")?;
            if let Some(data_bytes) = frame.data_ref() {
                sse_buffer.extend_from_slice(data_bytes);

                // Process complete SSE events (split on "\n\n")
                while let Some(event_end) = Self::find_sse_event_boundary(&sse_buffer) {
                    let event_bytes: Vec<u8> = sse_buffer.drain(..event_end).collect();
                    // Drain the trailing "\n\n"
                    if sse_buffer.len() >= 2 {
                        sse_buffer.drain(..2);
                    }

                    Self::handle_sse_event(&event_bytes, &mut state, handler, &self.model)?;
                }
            }
        }

        // Emit any pending tool call on stream end
        openai_emit_pending_tool_call(&mut state, handler)?;
        Ok(())
    }

    /// Find the boundary of an SSE event (`\n\n` delimiter).
    ///
    /// Returns the index just before the first `\n\n`, or `None` if not found.
    #[allow(clippy::manual_find)]
    fn find_sse_event_boundary(buf: &[u8]) -> Option<usize> {
        // SSE uses "\n\n" (or "\r\n\r\n") to delimit events
        for i in 0..buf.len().saturating_sub(1) {
            if buf[i] == b'\n' && buf[i + 1] == b'\n' {
                return Some(i);
            }
        }
        None
    }

    /// Parse and handle a single SSE event.
    ///
    /// SSE events have lines like:
    /// ```text
    /// data: {"choices": [...]}
    /// ```
    /// or:
    /// ```text
    /// data: [DONE]
    /// ```
    fn handle_sse_event(
        event_bytes: &[u8],
        state: &mut OpenAiStreamState,
        handler: &mut SseHandler,
        model: &Model,
    ) -> Result<()> {
        // Split event into lines and process each "data:" line
        let event_str = std::str::from_utf8(event_bytes).context("SSE event is not valid UTF-8")?;

        for line in event_str.lines() {
            let line = line.trim();
            if let Some(data_str) = line.strip_prefix("data:") {
                let data_str = data_str.trim();
                if data_str == "[DONE]" {
                    // Stream finished
                    continue;
                }
                // Parse the JSON value
                let value: Value =
                    serde_json::from_str(data_str).context("Failed to parse SSE data as JSON")?;
                debug!("llama-sse: {value}");
                harnx_core::llm_trace::stream_event("llama-server", &value);
                openai_handle_stream_event(state, handler, &value, model)?;
            }
        }

        Ok(())
    }
}

#[cfg(unix)]
#[async_trait::async_trait]
impl crate::Client for crate::LlamaServerClient {
    fn extra_config(&self) -> Option<&harnx_core::api_types::ExtraConfig> {
        self.config.extra.as_ref()
    }

    fn patches_config(&self) -> Option<&harnx_core::model::RequestPatches> {
        self.config.patches.as_ref()
    }

    fn name(&self) -> &str {
        &self.config.name
    }

    fn model(&self) -> &Model {
        &self.model
    }

    fn model_mut(&mut self) -> &mut Model {
        &mut self.model
    }

    async fn chat_completions_inner(
        &self,
        _client: &reqwest::Client, // Unused — transport is UDS via hyperlocal
        data: ChatCompletionsData,
    ) -> Result<ChatCompletionsOutput> {
        // Build request body using OpenAI mapping
        let mut body = openai_build_chat_completions_body(data, &self.model);

        // Ensure stream: false for non-streaming request
        body["stream"] = Value::Bool(false);

        let response_bytes = self.post_json("/v1/chat/completions", &body).await?;

        let response: Value = serde_json::from_slice(&response_bytes)
            .context("Failed to parse chat completions response")?;

        debug!("llama-response: {response}");
        harnx_core::llm_trace::response("llama-server", &response);

        openai_extract_chat_completions(&response, &self.model)
    }

    async fn chat_completions_streaming_inner(
        &self,
        _client: &reqwest::Client, // Unused — transport is UDS via hyperlocal
        handler: &mut SseHandler,
        data: ChatCompletionsData,
    ) -> Result<()> {
        // Build request body using OpenAI mapping
        let mut body = openai_build_chat_completions_body(data, &self.model);

        // Enable streaming with usage reporting
        body["stream"] = Value::Bool(true);
        body["stream_options"] = serde_json::json!({"include_usage": true});

        self.post_json_streaming("/v1/chat/completions", &body, handler)
            .await
    }
}

#[cfg(test)]
#[cfg(unix)]
mod tests {
    use super::*;
    use crate::ChatCompletionsData;
    use harnx_core::abort::create_abort_signal;
    use tokio::sync::mpsc;

    #[test]
    fn test_openai_build_chat_completions_body_basic() {
        use harnx_core::message::{Message, MessageContent, MessageRole};

        let model = Model::new("llama-server", "test-model");
        let data = ChatCompletionsData {
            messages: vec![Message {
                role: MessageRole::User,
                content: MessageContent::Text("Hello".to_string()),
                ..Default::default()
            }],
            temperature: None,
            top_p: None,
            functions: None,
            stream: false,
            attachments_dir: None,
        };

        let body = openai_build_chat_completions_body(data, &model);
        assert_eq!(body["model"], "test-model");
        assert!(body.get("messages").is_some());
    }

    #[test]
    fn test_handle_sse_event_content_delta() {
        let (tx, _rx) = mpsc::unbounded_channel();
        let abort = create_abort_signal();
        let mut handler = crate::SseHandler::new(tx, abort);
        let mut state = OpenAiStreamState::default();

        // Single SSE event with content delta
        let event = b"data: {\"choices\":[{\"delta\":{\"content\":\"Hello\"}}]}";
        crate::LlamaServerClient::handle_sse_event(
            event,
            &mut state,
            &mut handler,
            &Model::new("llama-server", "test-model"),
        ).unwrap();

        let (buffer, _thought, _tool_calls, _usage) = handler.take();
        assert!(buffer.contains("Hello"));
    }

    #[test]
    fn test_handle_sse_event_tool_call() {
        let (tx, _rx) = mpsc::unbounded_channel();
        let abort = create_abort_signal();
        let mut handler = crate::SseHandler::new(tx, abort);
        let mut state = OpenAiStreamState::default();

        // Simulate tool call arguments accumulating across multiple chunks
        let events = [
            b"data: {\"choices\":[{\"delta\":{\"tool_calls\":[{\"index\":0,\"id\":\"call_1\",\"function\":{\"name\":\"test_func\",\"arguments\":\"\"}}]}}]}".as_slice(),
            b"data: {\"choices\":[{\"delta\":{\"tool_calls\":[{\"index\":0,\"function\":{\"arguments\":\"{\\\"arg1\\\": \"}}]}}]}".as_slice(),
            b"data: {\"choices\":[{\"delta\":{\"tool_calls\":[{\"index\":0,\"function\":{\"arguments\":\"\\\"value\\\"}\"}}]}}]}".as_slice(),
        ];

        for event in events {
            crate::LlamaServerClient::handle_sse_event(
            event,
            &mut state,
            &mut handler,
            &Model::new("llama-server", "test-model"),
        ).unwrap();
        }

        // Finalize pending tool call
        openai_emit_pending_tool_call(&mut state, &mut handler).unwrap();

        let (_buffer, _thought, tool_calls, _usage) = handler.take();
        assert_eq!(tool_calls.len(), 1);
        assert_eq!(tool_calls[0].name, "test_func");
    }

    #[test]
    fn test_handle_sse_event_done_marker() {
        let (tx, _rx) = mpsc::unbounded_channel();
        let abort = create_abort_signal();
        let mut handler = crate::SseHandler::new(tx, abort);
        let mut state = OpenAiStreamState::default();

        // Process a tool call first
        let tool_event = b"data: {\"choices\":[{\"delta\":{\"tool_calls\":[{\"index\":0,\"id\":\"tc1\",\"function\":{\"name\":\"test_func\",\"arguments\":\"\"}}]}}]}";
        crate::LlamaServerClient::handle_sse_event(
            tool_event,
            &mut state,
            &mut handler,
            &Model::new("llama-server", "test-model"),
        ).unwrap();

        // Then [DONE] marker
        let event_done = b"data: [DONE]";
        crate::LlamaServerClient::handle_sse_event(
            event_done,
            &mut state,
            &mut handler,
            &Model::new("llama-server", "test-model"),
        ).unwrap();

        // Finalize pending tool call
        openai_emit_pending_tool_call(&mut state, &mut handler).unwrap();

        let (_buffer, _thought, tool_calls, _usage) = handler.take();
        assert_eq!(tool_calls.len(), 1);
        assert_eq!(tool_calls[0].name, "test_func");
    }

    #[test]
    fn test_openai_build_chat_completions_body_includes_tools() {
        use harnx_core::tool::{JsonSchema, ToolDeclaration};

        let model = Model::new("llama-server", "test-model");
        let data = ChatCompletionsData {
            messages: vec![],
            temperature: None,
            top_p: None,
            functions: Some(vec![ToolDeclaration {
                name: "get_weather".to_string(),
                description: "Get weather".to_string(),
                parameters: JsonSchema::default(),
                mcp_tool_name: None,
                mcp_server_name: None,
                call_template: None,
                result_template: None,
                idempotent_hint: None,
                read_only_hint: None,
            }]),
            stream: false,
            attachments_dir: None,
        };

        let body = openai_build_chat_completions_body(data, &model);
        assert!(body.get("tools").is_some());
        let tools = body["tools"].as_array().expect("tools should be an array");
        assert_eq!(tools.len(), 1);
        assert_eq!(tools[0]["function"]["name"], "get_weather");
    }

    /// Test multi-event SSE stream (data split across boundaries).
    #[test]
    fn test_handle_sse_event_multiple_data_lines() {
        let (tx, _rx) = mpsc::unbounded_channel();
        let abort = create_abort_signal();
        let mut handler = crate::SseHandler::new(tx, abort);
        let mut state = OpenAiStreamState::default();

        // Event with two valid data lines (each parsed separately)
        let event =
            b"data: {\"choices\":[{\"delta\":{\"content\":\"Part1\"}}]}\ndata: {\"choices\":[{\"delta\":{\"content\":\"Part2\"}}]}";
        crate::LlamaServerClient::handle_sse_event(
            event,
            &mut state,
            &mut handler,
            &Model::new("llama-server", "test-model"),
        ).unwrap();

        let (buffer, _thought, _tool_calls, _usage) = handler.take();
        assert!(buffer.contains("Part1"));
        assert!(buffer.contains("Part2"));
    }

    /// Test that `stream_options` is added correctly for streaming requests.
    #[test]
    fn test_streaming_request_includes_stream_options() {
        let model = Model::new("llama-server", "test-model");
        let data = ChatCompletionsData {
            messages: vec![],
            temperature: None,
            top_p: None,
            functions: None,
            stream: true,
                attachments_dir: None,
        };

        let mut body = openai_build_chat_completions_body(data, &model);
        body["stream"] = Value::Bool(true);
        body["stream_options"] = serde_json::json!({"include_usage": true});

        assert_eq!(body["stream"], Value::Bool(true));
        assert_eq!(body["stream_options"]["include_usage"], Value::Bool(true));
    }
}
