#[cfg(unix)]
pub mod client;
#[cfg(not(unix))]
pub mod client_unsupported;
#[cfg(unix)]
pub mod config_test;
#[cfg(unix)]
pub mod process;

// The LlamaServerClient struct is generated by the register_client! macro in lib.rs.
// This module provides:
// - client.rs: Additional impl block for LlamaServerClient with PROMPTS and helper methods
// - process.rs: subprocess management with global registry

#[cfg(windows)]
pub mod process {
    use anyhow::{bail, Result};

    #[derive(Debug, Clone)]
    pub struct LlamaServerProcessConfig;

    #[derive(Debug)]
    pub struct LlamaServerProcessManager;

    impl LlamaServerProcessManager {
        pub fn new(_config: LlamaServerProcessConfig) -> Result<Self> {
            bail!("llama-server provider requires a Unix platform (uses unix domain sockets)")
        }
    }
}
