use crate::server::{
    BashServer, ExecCommandParams, ReadExecLogParams, RollbackParams, SpawnCommandParams,
    TerminateParams, WaitParams,
};
use crate::tool_templates;
use async_trait::async_trait;
use harnx_sandbox_common::SandboxConfig;
use harnx_toolset::{ToolInvokeError, ToolSpec, Toolset};
use rmcp::model::{CallToolResult, ErrorCode, ErrorData, Tool};
use rmcp::schemars::JsonSchema;
use serde::de::DeserializeOwned;
use serde_json::{Map, Value};
use tokio_util::sync::CancellationToken;

/// Native toolset for sandboxed command execution and process management.
#[derive(Clone)]
pub struct BashToolset {
    server: BashServer,
}

impl BashToolset {
    /// Build a toolset from resolved filesystem permissions and sandbox configuration.
    pub async fn new(sandbox_config: SandboxConfig) -> Self {
        let server = BashServer::new_with_sandbox(sandbox_config);
        server.initialize_allowlist().await;
        Self { server }
    }

    /// Remove temporary execution logs created by this toolset instance.
    pub fn cleanup_log_dir(&self) -> std::io::Result<()> {
        self.server.cleanup_log_dir()
    }
}

fn input_schema<T: JsonSchema + 'static>() -> Value {
    Tool::new("schema", "schema", Map::new())
        .with_input_schema::<T>()
        .schema_as_json_value()
}

fn spec<T: JsonSchema + 'static>(name: &str, description: &str, call_template: &str) -> ToolSpec {
    ToolSpec {
        name: name.to_string(),
        description: description.to_string(),
        input_schema: input_schema::<T>(),
        idempotent_hint: false,
        read_only_hint: false,
        timeout_secs: None,
        meta: None,
    }
    .with_call_template(call_template)
}

fn parse_args<T: DeserializeOwned>(args: Value) -> Result<T, ToolInvokeError> {
    serde_json::from_value(args)
        .map_err(|err| ToolInvokeError::Recoverable(format!("invalid tool arguments: {err}")))
}

fn map_result(result: Result<CallToolResult, ErrorData>) -> Result<Value, ToolInvokeError> {
    match result {
        Ok(result) => serde_json::to_value(result).map_err(|err| {
            ToolInvokeError::Fatal(format!("failed to serialize tool result: {err}"))
        }),
        Err(err) if err.code == ErrorCode::INTERNAL_ERROR => {
            Err(ToolInvokeError::Fatal(err.message.to_string()))
        }
        Err(err) => Err(ToolInvokeError::Recoverable(err.message.to_string())),
    }
}

#[async_trait]
impl Toolset for BashToolset {
    fn name(&self) -> &str {
        "bash"
    }

    fn tools(&self) -> Vec<ToolSpec> {
        vec![
            spec::<ExecCommandParams>(
                "exec",
                "Execute a command and return truncated combined stdout/stderr. When output is cropped, stdout/stderr temp log files are included for later retrieval. Prefer head_lines/tail_lines/max_output_bytes params over piping to head/tail in the command string. Supports shebang lines: if the command starts with #!, the script is written to a temp file and executed with the named interpreter (python3, node, ruby, etc.) — prefer this over python3 -c or node -e for multi-line scripts.",
                tool_templates::EXEC_CALL,
            ),
            spec::<ReadExecLogParams>(
                "read_exec_log",
                "Read a temp stdout/stderr log file generated by this bash server. Use execution_id from exec/wait response with stream 'stdout' or 'stderr'. Supports offset/limit/tail/grep/head_lines/tail_lines/max_output_bytes, but only for server-owned temp logs.",
                tool_templates::READ_EXEC_LOG_CALL,
            ),
            spec::<SpawnCommandParams>(
                "spawn",
                "Spawn a background command. Returns an execution_id and log file paths immediately without waiting for the command to finish. Output is written to separate stdout.log and stderr.log files. Use 'wait' to check for completion and 'terminate' to stop it. Supports shebang lines: if the command starts with #!, the script is executed with the named interpreter automatically.",
                tool_templates::SPAWN_CALL,
            ),
            spec::<WaitParams>(
                "wait",
                "Wait for a spawned background process to exit. Returns the exit code, output metrics, and truncated output. If the process does not exit within the timeout, returns its current status and partial output without killing it. Use head_lines/tail_lines/grep to filter output rather than post-processing with shell tools.",
                tool_templates::WAIT_CALL,
            ),
            spec::<TerminateParams>(
                "terminate",
                "Send a signal to a spawned background process. Default signal is SIGTERM. Supported signals: SIGTERM, SIGKILL, SIGINT, SIGHUP.",
                tool_templates::TERMINATE_CALL,
            ),
            spec::<RollbackParams>(
                "rollback_file",
                "Restore a repository to a prior harnx history snapshot. Pass the commit SHA from the 'commit <sha>' line at the top of a prior tool response's diff as the commit_id parameter.",
                tool_templates::ROLLBACK_FILE_CALL,
            ),
        ]
    }

    async fn invoke(
        &self,
        tool: &str,
        args: Value,
        _cancel: CancellationToken,
    ) -> Result<Value, ToolInvokeError> {
        let result = match tool {
            "exec" => self.server.exec_command_impl(parse_args(args)?).await,
            "read_exec_log" => self.server.read_exec_log_impl(parse_args(args)?).await,
            "spawn" => self.server.spawn_impl(parse_args(args)?).await,
            "wait" => self.server.wait_impl(parse_args(args)?).await,
            "terminate" => self.server.terminate_impl(parse_args(args)?).await,
            "rollback_file" => self.server.rollback_file_impl(parse_args(args)?).await,
            _ => {
                return Err(ToolInvokeError::Recoverable(format!(
                    "unknown bash tool: {tool}"
                )));
            }
        };
        map_result(result)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use harnx_tool_allow::ResolvedAllowlist;
    use serde_json::json;
    use std::path::PathBuf;
    use std::sync::Arc;

    #[test]
    fn maps_server_errors_by_error_code() {
        let internal = map_result(Err(ErrorData::internal_error("server failed", None)));
        assert!(matches!(internal, Err(ToolInvokeError::Fatal(_))));

        let invalid = map_result(Err(ErrorData::invalid_params("bad input", None)));
        assert!(matches!(invalid, Err(ToolInvokeError::Recoverable(_))));
    }

    fn sandbox_config(enabled: bool) -> SandboxConfig {
        SandboxConfig {
            enabled,
            allowlist: Arc::new(ResolvedAllowlist::new()),
            extra_env_passthrough: vec![],
            env_overrides: vec![],
            sandbox_run_path: PathBuf::from("harnx-sandbox-exec"),
        }
    }

    async fn test_toolset(
        paths: Vec<PathBuf>,
        mut config: SandboxConfig,
        _legacy_default: bool,
    ) -> BashToolset {
        let mut allowlist = ResolvedAllowlist::new();
        for path in paths {
            allowlist.insert_rwx(path);
        }
        config.allowlist = Arc::new(allowlist);
        BashToolset::new(config).await
    }

    #[tokio::test]
    async fn exposes_exact_bash_tools() {
        let root = tempfile::tempdir().unwrap();
        let toolset = test_toolset(
            vec![root.path().to_path_buf()],
            sandbox_config(false),
            false,
        )
        .await;

        assert_eq!(toolset.name(), "bash");
        let tools = toolset.tools();
        assert_eq!(
            tools
                .iter()
                .map(|tool| tool.name.as_str())
                .collect::<Vec<_>>(),
            [
                "exec",
                "read_exec_log",
                "spawn",
                "wait",
                "terminate",
                "rollback_file"
            ]
        );
        assert!(tools.iter().all(|tool| {
            tool.input_schema.get("type") == Some(&json!("object"))
                && !tool.idempotent_hint
                && !tool.read_only_hint
        }));
    }

    #[cfg(unix)]
    #[tokio::test]
    async fn invokes_exec_with_cli_root_without_sandbox_helper() {
        let root = tempfile::tempdir().unwrap();
        let toolset = test_toolset(
            vec![root.path().to_path_buf()],
            sandbox_config(false),
            false,
        )
        .await;

        let result = toolset
            .invoke(
                "exec",
                json!({
                    "command": "printf native-toolset",
                    "working_dir": root.path().to_string_lossy()
                }),
                CancellationToken::new(),
            )
            .await
            .unwrap();
        assert_ne!(result.get("isError"), Some(&Value::Bool(true)));
        assert!(result.to_string().contains("native-toolset"));
    }

    #[tokio::test]
    async fn rejects_unknown_tool() {
        let root = tempfile::tempdir().unwrap();
        let toolset = test_toolset(
            vec![root.path().to_path_buf()],
            sandbox_config(false),
            false,
        )
        .await;
        let result = toolset
            .invoke("missing", json!({}), CancellationToken::new())
            .await;
        assert!(matches!(result, Err(ToolInvokeError::Recoverable(_))));
    }
}
